name: sync client to main repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github main repository
        uses: actions/checkout@v3
        with:
          repository: ablej-ssafy/ai-headhunting
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "sunsuking"
          git config --global user.email "sunsuking@gmail.com"

      - name: Add client as subtree
        run: |
          git remote add client https://github.com/ablej-ssafy/client.git
          git fetch client main
          git subtree pull --prefix=client client main --message "Sync client to main repository"

      - name: Push changes to Github
        run: |
          git push origin main
